services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: featureflag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P05t6r3SQL_1994
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
