spring:
  application:
    name: "featureflag"

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

jwt:
  secret: MyVerySecretKey12345678901234567890
  expirationMs: 86400000

# Swagger
springdoc:
  api-docs:
    enabled: true

  #spring.security.user.name: admin
#spring.security.user.password: admin.
#jwt.secret: BytesColab4P!
#jwt.expiration: 3600000
