spring:
  config:
    import: optional:file:.env.[properties]
  application:
    name: "featureflag"
  profiles:
    active: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080

jwt:
  secret: MyVerySecretKey12345678901234567890
  expirationMs: 86400000

# Swagger
springdoc:
  api-docs:
    enabled: true

# Logging
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.bytescolab.featureflag: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
