jwt:
  secret: MyVerySecretKey12345678901234567890
  expirationMs: 86400000

server.port: 8080
#spring.security.user.name: admin
#spring.security.user.password: admin.
#jwt.secret: BytesColab4P!
#jwt.expiration: 3600000

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/featureflag
    username: postgres
    password: P05t6r3SQL_1994
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

# Swagger
springdoc:
  api-docs:
    enabled: true